feat: new complete version of "Svelte SEO" (#45)
* Initial commit

* Added the title property

* Added description tag

* Added applicationName property

* Added theme color and application name meta tags

* Added noindex and nofollow

* added nositelinkssearchbox

* Added notranslate

* Added canonical and amp

* Added manifest and languageAlternates tags

* Added the keywords tag

* Adding twitter tags

* Done with the twitter tags

* added opengraph component

* Run prettier on the files

* Addedtests

* Written tests for openGraph.music

* run prettier on files

* run all tests

* Added husky

* fixed linting issues

* removed cache file

* Merged new branch into master

* Add eslintcache to gitignore

* reverted prettier to default

* Added travis.yml

* Delete .prettierrc

* Run the default prettier config

* Updated dependencies

* Added other pages

* Working on readme

* Removed un-needed files

* Reformating readme

* Fixed grammartical errors

* Fixing formatting in markdown

* The component now accepts a default slot

* Formatting markdown

* Update README.md

* Delete .eslintcache

* Fixed eslint config

* Added jsonLd

* Fixed Error: Cannot find name 'SvelteSeo'.

* Changed to yarn from pnpm

* Now uses yarn

* Updated to use yarn. All tests passes

* Fixed formating in Travis CI

* trying to fix travis

* Changed node version to 18

* Removed format from travis.yml

* reducing node version to 16

* Adding `npm run format` to travis.yml

* Removed format from travis

* Update package.json

* Changed package version

* Added license

* Fixed tests

* Uses SvelteSeo instead of head

* Added toc to doc

* Added playwright install to `before_script`

* Formatted files